config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  get "/:slug", to: "articles#show", as: :article

  namespace :admin do
    get "/dashboard", to: "dashboard#index", as: :dashboard
    resources :articles
    resources :labels
    resources :social_links
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  # Associations
  has_many :article_labels
  has_many :labels, through: :article_labels

  # Validations
  validates :title, presence: true
  validates :body, presence: true
  validates :published_on, presence: true
  validates :slug, presence: true, uniqueness: true

  # ActiveText
  has_rich_text :body

  # Scopes
  scope :latest, -> { order(published_on: :desc) }

  # Callbacks
  before_validation :set_slug, on: :create

  private

  def set_slug
    return if title.blank?

    self.slug = title.parameterize
  end
end

app/models/article_label.rb
# frozen_string_literal: true

class ArticleLabel < ApplicationRecord
  # Associations
  belongs_to :article
  belongs_to :label
end

app/models/label.rb
# frozen_string_literal: true

class Label < ApplicationRecord
  # Associations
  has_many :article_labels
  has_many :articles, through: :article_labels

  # Validations
  validates :name, presence: true

  # Callbacks
  before_destroy :check_for_articles, prepend: true

  private

  def check_for_articles
    return unless articles.any?

    errors.add(:base, "Cannot delete label while articles exist that reference it")
    throw :abort
  end
end

app/models/social_link.rb
# frozen_string_literal: true

class SocialLink < ApplicationRecord
  # Validations
  validates :caption, presence: true
  validates :href, presence: true
  validates :svg_path, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :validatable
end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true

module Admin
  class ArticlesController < AdminController
    before_action :set_article, only: %w[edit update destroy]

    def index
      @articles = Article.all.order(published_on: :desc)
    end

    def new
      @article = Article.new(published_on: Date.today)
    end

    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to admin_articles_path, notice: "Sucessfully created article."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @article.update(article_params)
        redirect_to admin_articles_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @article.destroy
        redirect_to admin_articles_path, notice: "Sucessfully deleted article."
      else
        redirect_to admin_articles_path, alert: @article.errors.full_messages.join(", ")
      end
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :slug, :published_on, :body, label_ids: [])
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardController < AdminController
    def index; end
  end
end

app/controllers/admin/labels_controller.rb
# frozen_string_literal: true

module Admin
  class LabelsController < AdminController
    before_action :set_label, only: %w[edit update destroy]

    def index
      @labels = Label.all.order(name: :asc)
    end

    def new
      @label = Label.new
    end

    def create
      @label = Label.new(label_params)

      if @label.save
        redirect_to admin_labels_path, notice: "Sucessfully created label."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @label.update(label_params)
        redirect_to admin_labels_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @label.destroy
        redirect_to admin_labels_path, notice: "Sucessfully deleted label."
      else
        redirect_to admin_labels_path, alert: @label.errors.full_messages.join(", ")
      end
    end

    private

    def set_label
      @label = Label.find(params[:id])
    end

    def label_params
      params.require(:label).permit(:name)
    end
  end
end

app/controllers/admin/social_links_controller.rb
# frozen_string_literal: true

module Admin
  class SocialLinksController < AdminController
    before_action :set_social_link, only: %w[edit update destroy]

    def index
      @social_links = SocialLink.all.order(caption: :asc)
    end

    def new
      @social_link = SocialLink.new
    end

    def create
      @social_link = SocialLink.new(social_link_params)

      if @social_link.save
        redirect_to admin_social_links_path, notice: "Sucessfully created social link."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @social_link.update(social_link_params)
        redirect_to admin_social_links_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @social_link.destroy
        redirect_to admin_social_links_path, notice: "Sucessfully deleted social link."
      else
        redirect_to admin_social_links_path, alert: @social_link.errors.full_messages.join(", ")
      end
    end

    private

    def set_social_link
      @social_link = SocialLink.find(params[:id])
    end

    def social_link_params
      params.require(:social_link).permit(:caption, :href, :svg_path)
    end
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_social_links

  private

  def set_social_links
    @social_links = SocialLink.all.order(caption: :asc)
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def show
    @article = Article.find_by(slug: params[:slug])
    not_found unless @article.present?
  end

  private

  def not_found
    raise ActionController::RoutingError, "Not Found"
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @articles = Article.latest.includes(:labels)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
  class MenuItem
    attr_accessor :name, :path, :controller

    def initialize(name:, path:, controller:)
      @name = name
      @path = path
      @controller = controller
    end
  end

  def admin_menu_items
    [
      MenuItem.new(name: "Dashboard", path: admin_dashboard_path, controller: "admin/dashboard"),
      MenuItem.new(name: "Articles", path: admin_articles_path, controller: "admin/articles"),
      MenuItem.new(name: "Labels", path: admin_labels_path, controller: "admin/labels"),
      MenuItem.new(name: "Social Links", path: admin_social_links_path, controller: "admin/social_links")
    ]
  end

  def admin_menu_item_class(path)
    if current_page?(path)
      "bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium"
    else
      "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"
    end
  end

  def active_admin_menu_item
    admin_menu_items.find { |menu_item| menu_item.controller == params[:controller] || menu_item.path == request.path }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/articles/_article.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 text-sm font-medium text-gray-900 sm:pl-0 w-1/6"><%= article.published_on %></td>
  <td class="whitespace-nowrap py-4 text-sm text-gray-500 w-5/6"><%= article.title %></td>
  <td class="relative whitespace-nowrap py-4 text-right text-sm font-medium sm:pr-0 flex gap-8">
    <%= button_to 'Delete', admin_article_path(article), method: :delete, class: 'text-red-600 hover:text-red-900' %>
    <%= link_to 'Edit', edit_admin_article_path(article), class: 'text-indigo-600 hover:text-indigo-900' %>
  </td>
</tr>

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |f| %>
  <div class="w-1/2 mb-4">
    <%= f.label :title, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.text_field :title, autofocus: true, class: 'peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>
  </div>

  <div class="w-1/2 mb-4">
    <%= f.label :slug, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.text_field :slug, autofocus: true, class: 'peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>
  </div>

  <div class="w-1/4 mb-4">
    <%= f.label :published_on, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.date_field :published_on, autofocus: true, class: 'peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>
  </div>

  <div class="w-1/4 mb-4">
    <%= f.label :labels, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <%= f.collection_check_boxes :label_ids, Label.all, :id, :name do |b| %>
      <div class="flex items-center">
        <%= b.check_box(class: 'peer h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded') %>
        <%= b.label class: 'ml-3 block text-sm font-medium text-gray-700' %>
      </div>
    <% end %>
  </div>

  <div class="w-full mb-4">
    <%= f.label :body, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.rich_text_area :body, autofocus: true, class: 'h-48 peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>
  </div>

  <div class="flex gap-8 items-center">
    <%= f.submit class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
    <%= link_to 'Cancel', admin_articles_path, class: 'rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50' %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="flex justify-end">
    <%= link_to 'Add new article', new_admin_article_path, class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
  </div>

  <div class="flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0 w-48">Published On</th>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0 w-48">Title</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <%= render @articles %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/articles/new.html.erb
<%= render 'form' %>

app/views/admin/dashboard/index.html.erb
Admin

app/views/admin/labels/_form.html.erb
<%= form_for [:admin, @label] do |f| %>
  <div class="w-1/3 mb-4">
    <%= f.label :name, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.text_field :name, autofocus: true, class: 'peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>

  </div>

  <div class="flex gap-8 items-center">
    <%= f.submit class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
    <%= link_to 'Cancel', admin_labels_path, class: 'rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50' %>
  </div>
<% end %>

app/views/admin/labels/_label.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 text-sm font-medium text-gray-900 sm:pl-0 w-full"><%= label.name %></td>
  <td class="relative whitespace-nowrap py-4 text-right text-sm font-medium sm:pr-0 flex gap-8">
    <%= button_to 'Delete', admin_label_path(label), method: :delete, class: 'text-red-600 hover:text-red-900' %>
    <%= link_to 'Edit', edit_admin_label_path(label), class: 'text-indigo-600 hover:text-indigo-900' %>
  </td>
</tr>

app/views/admin/labels/edit.html.erb
<%= render 'form' %>

app/views/admin/labels/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="flex justify-end">
    <%= link_to 'Add new label', new_admin_label_path, class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
  </div>

  <div class="flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0 w-48">Name</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <%= render @labels %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/labels/new.html.erb
<%= render 'form' %>

app/views/admin/social_links/_form.html.erb
<%= form_for [:admin, @social_link] do |f| %>
  <div class="w-1/3 mb-4">
    <%= f.label :caption, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.text_field :caption, autofocus: true, class: 'peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>
  </div>

  <div class="w-1/3 mb-4">
    <%= f.label :href, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.text_field :href, autofocus: true, class: 'peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>
  </div>

  <div class="w-1/3 mb-4">
    <%= f.label :svg_path, class: 'block text-sm font-medium leading-6 text-gray-900' %>

    <div class="relative mt-2">
      <%= f.text_field :svg_path, autofocus: true, class: 'peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0 sm:text-sm sm:leading-6' %>
      <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
    </div>
  </div>

  <div class="flex gap-8 items-center">
    <%= f.submit class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
    <%= link_to 'Cancel', admin_social_links_path, class: 'rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50' %>
  </div>
<% end %>

app/views/admin/social_links/_social_link.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 text-sm font-medium text-gray-900 sm:pl-0 w-1/4"><%= social_link.caption %></td>
  <td class="whitespace-nowrap py-4 text-sm text-gray-500 w-1/2"><%= social_link.href %></td>
  <td class="whitespace-nowrap py-4 text-sm text-gray-500 w-1/4"><%= social_link.svg_path %></td>
  <td class="relative whitespace-nowrap py-4 text-right text-sm font-medium sm:pr-0 flex gap-8">
    <%= button_to 'Delete', admin_social_link_path(social_link), method: :delete, class: 'text-red-600 hover:text-red-900' %>
    <%= link_to 'Edit', edit_admin_social_link_path(social_link), class: 'text-indigo-600 hover:text-indigo-900' %>
  </td>
</tr>

app/views/admin/social_links/edit.html.erb
<%= render 'form' %>

app/views/admin/social_links/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="flex justify-end">
    <%= link_to 'Add new social link', new_admin_social_link_path, class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer' %>
  </div>

  <div class="flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0 w-48">Caption</th>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0 w-48">Href</th>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0 w-48">Svg Path</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <%= render @social_links %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/social_links/new.html.erb
<%= render 'form' %>

app/views/articles/_article.html.erb
<article class="scroll-mt-16 pb-0">
  <div>
    <header class="relative mb-10 xl:mb-0">
      <div class="pointer-events-none absolute left-[max(-0.5rem,calc(50%-18.625rem))] top-0 z-50 flex h-4 items-center justify-end gap-x-2 lg:left-0 lg:right-[calc(max(2rem,50%-38rem)+40rem)] lg:min-w-[32rem] xl:h-8">
        <a class="inline-flex" href="#commit-message-suggestions">
          <%= link_to article_path(article.slug), class: 'inline-flex' do %>
            <time datetime="<%= article.published_on %>" class="font-mono hidden xl:pointer-events-auto xl:block xl:text-2xs/4 xl:font-medium xl:text-white/50"><%= article.published_on.strftime("%b %e, %Y") %></time>
          <% end %>
        </a>

        <div class="h-[0.0625rem] w-3.5 bg-gray-400 lg:-mr-3.5 xl:mr-0 xl:bg-gray-300"></div>
      </div>

      <div class="mx-auto max-w-7xl px-6 lg:flex lg:px-8">
        <div class="lg:ml-96 lg:flex lg:w-full lg:justify-end lg:pl-32">
          <div class="mx-auto max-w-lg lg:mx-0 lg:w-0 lg:max-w-xl lg:flex-auto">
            <div class="flex">
              <%= link_to article_path(article.slug), class: 'inline-flex' do %>
                <time datetime="<%= article.published_on %>" class="font-mono text-2xs/4 font-medium text-gray-500 dark:text-white/50 xl:hidden"><%= article.published_on %></time>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </header>

    <div class="mx-auto max-w-7xl px-6 lg:flex lg:px-8">
      <div class="lg:ml-96 lg:flex lg:w-full lg:justify-end lg:pl-32">
        <div class="mx-auto max-w-lg lg:mx-0 lg:w-0 lg:max-w-xl lg:flex-auto">

          <div class="-ml-5 pt-2 text-xs text-purple-700 font-bold font-mono">
            <span class="text-green-500 mr-1">➜</span>

            <span class="text-sky-500 mr-1">
              <%= link_to 'dominicgoulet.com', root_path, class: 'border-b-2 py-1 border-double border-transparent hover:border-sky-300 hover:text-sky-300' %>
            </span>

            <%= render article.labels %>

            <span class="text-yellow-500 mr-1">✗</span>
          </div>

          <div class="typography mt-4">
            <h2>
              <%= link_to article.title, article_path(article.slug), class: 'inline-flex border-b-4 py-1 border-transparent hover:border-yellow-100 hover:text-yellow-100' %>
            </h2>

            <p><%= article.body %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/articles/index.html.erb
<%= render @articles %>

app/views/articles/show.html.erb
<%= render @article %>

app/views/labels/_label.html.erb
<span class="mr-1">
  label:(<span class="text-red-500"><%= link_to label.name.downcase.gsub(' ', '_'), root_path, class: 'border-b-2 py-1 border-double border-transparent hover:border-red-600 hover:text-red-600' %></span>)
</span>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div data-type="<%= type %>" class="mb-6 group data-[type=notice]:bg-green-50 data-[type=alert]:bg-red-50 rounded-md p-4">
    <div class="flex">
      <div class="flex-shrink-0">
        <%= inline_svg_tag "#{type}.svg" %>
      </div>

      <div class="ml-3">
        <h3 class="text-sm font-medium group-data-[type=notice]:text-green-800 group-data-[type=alert]:text-red-800">
          <%= message %>
        </h3>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title>Dominic Goulet</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full">
    <div class="min-h-full">
      <div class="bg-gray-800 pb-32">
        <nav class="bg-gray-800">
          <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="border-b border-gray-700">
              <div class="flex h-16 items-center justify-between px-4 sm:px-0">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <%= image_tag 'dominic_goulet.jpg', class: 'inline-block h-8 w-8 rounded-full border-2 border-sky-300' %>
                  </div>

                  <div class="ml-10 flex items-baseline space-x-4">
                    <% admin_menu_items.each do |menu_item| %>
                      <%= link_to menu_item.name, menu_item.path, class: admin_menu_item_class(menu_item.path) %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </nav>

        <header class="py-10">
          <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold tracking-tight text-white">
              <%= active_admin_menu_item.name %>
            </h1>
          </div>
        </header>
      </div>

      <main class="-mt-32">
        <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
          <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6">
            <%= render 'layouts/flash' %>
            <%= yield %>
          </div>
        </div>
      </main>
    </div>
  </body>
</html>